name: Workflow TP1 messages linux

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        run: echo "Récupération du code source"
      - name: Check finished
        run: echo "Vérification terminée"
